spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
      - id: EMPLOYEE-SERVICE
        uri: lb://EMPLOYEE-SERVICE
        predicates:
          - Path=/emps/**
        filters :
          - AuthenticationFilter
        
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
          - Path=/user/**
        
      - id: SALARY-SERVICE
        uri: lb://SALARY-SERVICE
        predicates:
          - Path=/salary/**
        filters :
          - AuthenticationFilter
        
      discovery:
        locator:
          lower-case-service-id: true
       
      globalcors:
        cors-configurations:
          '[/**]':
                allowedOrigins: "*"
                allowedMethods: "*"
                allowedHeaders: "*"
